### ISSUE TITLE
nvme 2.5: segfault of `nvme list -o json` when the SN of the NVMe is empty

### ISSUE THREAD

**Issue by gwendalcr** [linux-nvme/nvme-cli#2117]
Working with a prototype NVMe where the SN is still empty (all 0s).
While nvme 1.6 reports spaces:

```
nvme list -o json
{
  "Devices" : [
    {
      "DevicePath" : "/dev/nvme0n1",
      "Firmware" : "xxx",
      "Index" : 0,
      "ModelNumber" : "yyy",
      "ProductName" : "Unknown device",
      "SerialNumber" : "                    ",
      "UsedBytes" : 256060514304,
      "MaximiumLBA" : 500118192,
      "PhysicalSize" : 256060514304,
      "SectorSize" : 512
    }
  ]
} 
```

With nvme 2.5 `list` does work without `-o json`:
```
nvme list
Node                  Generic               SN                   Model                                    Namespace  Usage                      Format           FW Rev
--------------------- --------------------- -------------------- ---------------------------------------- ---------- -------------------------- ---------------- --------
/dev/nvme0n1          /dev/ng0n1            (null)               yyy                          0x1        256.06  GB / 256.06  GB    512   B +  0 B   xxx
```

But `nvme list -o json` segfault. The crash happens in `json_object_new_string` because we send an empty string to the JSON library:
```
(gdb) bt
#0  0x00007e4c26061659 in ?? ()
#1  0x00007e4c260fc167 in json_object_new_string (s=0x0) at /build/brya-arc-t/tmp/portage/dev-libs/json-c-0.16-r1/work/json-c-0.16/json_object.c:1276
#2  0x000059af08fc7b19 in json_list_item (n=n@entry=0x59af0a8cbcb0) at ../nvme-cli-2.5/nvme-print-json.c:2613
#3  0x000059af08fc676c in json_simple_list (r=0x59af0a8cb370) at ../nvme-cli-2.5/nvme-print-json.c:2640
#4  json_print_list_items (r=0x59af0a8cb370) at ../nvme-cli-2.5/nvme-print-json.c:2655
#5  0x000059af08f97bb1 in list (argc=<optimized out>, argv=<optimized out>, cmd=<optimized out>, plugin=<optimized out>) at ../nvme-cli-2.5/nvme.c:3383
#6  0x000059af08fbf0af in handle_plugin (argc=argc@entry=3, argv=argv@entry=0x7ffcfe039f70, plugin=0x59af0901bc38 <builtin>) at ../nvme-cli-2.5/plugin.c:171
#7  0x000059af08f97a34 in main (argc=<optimized out>, argv=<optimized out>) at ../nvme-cli-2.5/nvme.c:9416
```

In the code we are not checking if the string can be empty - it has not changed on ToT:

```
tatic struct json_object *json_list_item(nvme_ns_t n)
{
  struct json_object *jdevice = json_create_object();
  char devname[128] = { 0 }; 
  char genname[128] = { 0 }; 

  int lba = nvme_ns_get_lba_size(n);
  uint64_t nsze = nvme_ns_get_lba_count(n) * lba; 
  uint64_t nuse = nvme_ns_get_lba_util(n) * lba; 

  nvme_dev_full_path(n, devname, sizeof(devname));
  nvme_generic_full_path(n, genname, sizeof(genname));

  json_object_add_value_int(jdevice, "NameSpace", nvme_ns_get_nsid(n));
  json_object_add_value_string(jdevice, "DevicePath", devname);
  json_object_add_value_string(jdevice, "GenericPath", genname);
  json_object_add_value_string(jdevice, "Firmware", nvme_ns_get_firmware(n));
  json_object_add_value_string(jdevice, "ModelNumber", nvme_ns_get_model(n));
  json_object_add_value_string(jdevice, "SerialNumber", nvme_ns_get_serial(n));
  json_object_add_value_uint64(jdevice, "UsedBytes", nuse);
  json_object_add_value_uint64(jdevice, "MaximumLBA", nvme_ns_get_lba_count(n));
  json_object_add_value_uint64(jdevice, "PhysicalSize", nsze);
  json_object_add_value_int(jdevice, "SectorSize", lba);

  return jdevice;
}
```

We are not segfault'ing in simple `nvme list` because we rely on `printf()`. Should we use `sprintf()` before sending the `nvme_ns_get...` to JSON library?

**Comment by igaw** [comment]
Should be fixed in v2.6 with:
fda312dc3aec ("json: fix seg. fault converting NULL to JSON string")
