### ISSUE TITLE
1.11.1: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [linux-nvme/nvme-cli#700]
Test suite executed in build tree looks like test suite is executing nvme command without path in that tree.
```
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test
/usr/bin/make -C tests/ run
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests'
Running nvme_attach_detach_ns_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
/bin/sh: nvme: command not found
TestNVMeAttachDetachNSCmd (nose2.loader.LoadTestsFailure) ... FAIL

======================================================================
FAIL: TestNVMeAttachDetachNSCmd (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
AssertionError: 127 != 0 : ERROR : nvme list-ctrl failed

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
/bin/sh: nvme: command not found
Exception ignored in: <function TestNVMeAttachDetachNSCmd.__del__ at 0x7fed1dc8c9d0>
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_attach_detach_ns_test.py", line 68, in __del__
  File "/usr/lib64/python3.8/unittest/case.py", line 912, in assertEqual
  File "/usr/lib64/python3.8/unittest/case.py", line 905, in _baseAssertEqual
AssertionError: 127 != 0
Running nvme_compare_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_compare_test.TestNVMeCompareCmd.test_nvme_compare ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_compare_test.TestNVMeCompareCmd.test_nvme_compare
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_compare_test.py", line 77, in test_nvme_compare
    assert_equal(self.nvme_write(), 0)
AssertionError: 127 != 0

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)
Running nvme_create_max_ns_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
/bin/sh: nvme: command not found
TestNVMeCreateMaxNS (nose2.loader.LoadTestsFailure) ... FAIL

======================================================================
FAIL: TestNVMeCreateMaxNS (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
AssertionError: 127 != 0 : ERROR : reading nvm capacity failed

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
Exception ignored in: <function TestNVMeCreateMaxNS.__del__ at 0x7f4d17c9c8b0>
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_create_max_ns_test.py", line 70, in __del__
AttributeError: 'TestNVMeCreateMaxNS' object has no attribute 'nsze'
Running nvme_error_log_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_error_log_test.TestNVMeErrorLogCmd.test_get_error_log ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_error_log_test.TestNVMeErrorLogCmd.test_get_error_log
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_error_log_test.py", line 63, in test_get_error_log
    assert_equal(self.get_error_log_ctrl(), 0)
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_error_log_test.py", line 59, in get_error_log_ctrl
    return self.get_error_log()
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_test.py", line 447, in get_error_log
    assert_equal(err, 0, "ERROR : nvme error log failed")
AssertionError: 127 != 0 : ERROR : nvme error log failed

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)
Running nvme_flush_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_flush_test.TestNVMeFlushCmd.test_nvme_flush ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_flush_test.TestNVMeFlushCmd.test_nvme_flush
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_flush_test.py", line 61, in test_nvme_flush
    assert_equal(self.nvme_flush(), 0)
AssertionError: 127 != 0

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)
nvme flush /dev/nvme0 -n 1
Running nvme_format_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
/bin/sh: nvme: command not found
TestNVMeFormatCmd (nose2.loader.LoadTestsFailure) ... FAIL

======================================================================
FAIL: TestNVMeFormatCmd (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
AssertionError: 127 != 0 : ERROR : nvme list-ctrl failed

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
/bin/sh: nvme: command not found
Exception ignored in: <function TestNVMeFormatCmd.__del__ at 0x7f37ababa9d0>
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_format_test.py", line 85, in __del__
  File "/usr/lib64/python3.8/unittest/case.py", line 912, in assertEqual
  File "/usr/lib64/python3.8/unittest/case.py", line 905, in _baseAssertEqual
AssertionError: 127 != 0
Running nvme_fw_log_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_fw_log_test.TestNVMeFwLogCmd.test_fw_log ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_fw_log_test.TestNVMeFwLogCmd.test_fw_log
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_fw_log_test.py", line 71, in test_fw_log
    assert_equal(self.get_fw_log(), 0)
AssertionError: 127 != 0

----------------------------------------------------------------------
Ran 1 test in 0.012s

FAILED (failures=1)


Running nvme_get_features_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_get_features_test.TestNVMeGetMandatoryFeatures.test_get_mandatory_features ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_get_features_test.TestNVMeGetMandatoryFeatures.test_get_mandatory_features
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_get_features_test.py", line 105, in test_get_mandatory_features
    self.get_mandatory_features(feature_id)
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_get_features_test.py", line 100, in get_mandatory_features
    assert_equal(proc.wait(), 0)
AssertionError: 127 != 0

----------------------------------------------------------------------
Ran 1 test in 0.012s

FAILED (failures=1)

Running nvme_id_ctrl_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_id_ctrl_test.TestNVMeIdctrlCmd.test_id_ctrl ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_id_ctrl_test.TestNVMeIdctrlCmd.test_id_ctrl
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_id_ctrl_test.py", line 55, in test_id_ctrl
    assert_equal(self.get_id_ctrl(), 0)
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_test.py", line 430, in get_id_ctrl
    assert_equal(err, 0, "ERROR : nvme id controller failed")
AssertionError: 127 != 0 : ERROR : nvme id controller failed

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)
nvme id-ctrl /dev/nvme0
Running nvme_id_ns_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
/bin/sh: nvme: command not found
TestNVMeIdentifyNamespace (nose2.loader.LoadTestsFailure) ... FAIL

======================================================================
FAIL: TestNVMeIdentifyNamespace (nose2.loader.LoadTestsFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
AssertionError: 127 != 0 : ERROR : nvme list namespace failed

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
Running nvme_read_write_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_read_write_test.TestNVMeReadWriteTest.test_nvme_write ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_read_write_test.TestNVMeReadWriteTest.test_nvme_write
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_read_write_test.py", line 70, in test_nvme_write
    assert_equal(self.nvme_write(), 0)
AssertionError: 127 != 0

----------------------------------------------------------------------
Ran 1 test in 0.014s

FAILED (failures=1)
Running nvme_simple_template_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_simple_template_test.TestNVMeSimpleTestTemplate.test_get_mandetory_features ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
Running nvme_smart_log_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_smart_log_test.TestNVMeSmartLogCmd.test_smart_log ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_smart_log_test.TestNVMeSmartLogCmd.test_smart_log
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_smart_log_test.py", line 85, in test_smart_log
    assert_equal(self.get_smart_log_ctrl(), 0)
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_smart_log_test.py", line 60, in get_smart_log_ctrl
    return self.get_smart_log("0xFFFFFFFF")
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_test.py", line 391, in get_smart_log
    assert_equal(err, 0, "ERROR : nvme smart log failed")
AssertionError: 127 != 0 : ERROR : nvme smart log failed

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)
nvme smart-log /dev/nvme0 -n 0xFFFFFFFF
Running nvme_test.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Running nvme_test_io.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Running nvme_test_logger.py

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Running nvme_writeuncor_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_writeuncor_test.TestNVMeUncor.test_write_uncor ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_writeuncor_test.TestNVMeUncor.test_write_uncor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_writeuncor_test.py", line 72, in test_write_uncor
    assert_equal(self.nvme_read(), 0)
AssertionError: 127 != 0

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (failures=1)
nvme read /dev/nvme0n1 --start-block=1023 --block-count=0 --data-size=512 --data=nvmetests//TestNVMeUncor/read_file.txt
Running nvme_writezeros_test.py
/sys/devices/pci0000:85/0000:85:00.0/0000:86:00.0/nvme/nvme0
nvme_writezeros_test.TestNVMeWriteZeros.test_write_zeros ... /bin/sh: nvme: command not found
FAIL

======================================================================
FAIL: nvme_writezeros_test.TestNVMeWriteZeros.test_write_zeros
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests/nvme_writezeros_test.py", line 97, in test_write_zeros
    assert_equal(self.nvme_write(), 0)
AssertionError: 127 != 0

----------------------------------------------------------------------
Ran 1 test in 0.014s

FAILED (failures=1)
make[1]: *** [Makefile:24: run] Error 1
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/nvme-cli-1.11.1/tests'
make: *** [Makefile:102: test] Error 2
```

**Comment by igaw** [comment]
No progress in this bug report for a long time. If you think it's still relevant please reopen.
